// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Weqpc2Y9rLzivO4LyQW1pY4RnOU1yQw',
    appId: '1:1077485891499:web:26768e80831e95f8dc2cee',
    messagingSenderId: '1077485891499',
    projectId: 'filmpal-auth',
    authDomain: 'filmpal-auth.firebaseapp.com',
    storageBucket: 'filmpal-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5MvEvMFZtu4INnzWnrjs4m8ASFZIK8a4',
    appId: '1:1077485891499:android:c20338c3132ae901dc2cee',
    messagingSenderId: '1077485891499',
    projectId: 'filmpal-auth',
    storageBucket: 'filmpal-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1z9d3tzgtg6dS9_vIauvlmUpUM0AjQyo',
    appId: '1:1077485891499:ios:98fe151222e75089dc2cee',
    messagingSenderId: '1077485891499',
    projectId: 'filmpal-auth',
    storageBucket: 'filmpal-auth.appspot.com',
    iosBundleId: 'com.example.filmpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1z9d3tzgtg6dS9_vIauvlmUpUM0AjQyo',
    appId: '1:1077485891499:ios:d5ecfc07d2cd8029dc2cee',
    messagingSenderId: '1077485891499',
    projectId: 'filmpal-auth',
    storageBucket: 'filmpal-auth.appspot.com',
    iosBundleId: 'com.example.filmpal.RunnerTests',
  );
}
